module.exports = {
  someSidebar: {
    "Project Overview": [
      "introduction", 
      "installation", 
      "setup", {
        "Download Data": [
          "downloadData",
          "dd_features", 
          "dd_ws_thermal_short",
          "dd_ws_thermal_long",
          "dd_ws_noise_and_privacy",
          "dd_ws_infection_risk",
          "dd_ws_movement",
          "dd_ws_privacy",
          "dd_ws_interaction",
        ],
      },
    ],
    "Customize Cozie": [
      "gettingStarted",
      "cloneCozie",
      "projectStructure",
      "iosOverview",
      "home",
      "viewsOne",
      "settings",
      "firebaseIntro",
      "secureFirebase",
      "researchKit",
      "notifications",
      "watchIntro",
      "watchMain",
      "watchSecondary",
      "validateDistribute",
      "testFlight",
      "documentationWebsite",
    ],
  },
};
