module.exports = {
  myAutogeneratedSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' means the current docs folder
    },
  ],
};
/*
module.exports = {
  someSidebar: {
    "Project Overview": [
      "introduction", 
      "installation", 
      "setup", {
        "Download Data": [
          "downloadData",
          "dd_features", 
          "dd_ws_thermal_short",
          "dd_ws_thermal_long",
          "dd_ws_noise_and_privacy",
          "dd_ws_infection_risk",
          "dd_ws_movement",
          "dd_ws_privacy",
          "dd_ws_interaction",
        ],
      },
    ],
    "Customize Cozie": [
      "gettingStarted",
      "cloneCozie",
      "projectStructure",
      "iosOverview",
      "home",
      "viewsOne",
      "settings",
      "firebaseIntro",
      "secureFirebase",
      "researchKit",
      "notifications",
      "watchIntro",
      "watchMain",
      "watchSecondary",
      "validateDistribute",
      "testFlight",
      "documentationWebsite",
    ],
    "Cozie v3": [
      "c3_introduction",
      "c3_getting_started",
      "c3_watch_survey",
      "c3_watch_survey_icons",
      "c3_features",
      "c3_qr_code",
    ],
  },
};
*/